# Generated by Django 5.1.2 on 2024-11-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                blank=True,
                choices=[("cash", "наличные"), ("transaction", "перевод")],
                default="transaction",
                max_length=20,
                null=True,
                verbose_name="Метод платежа",
            ),
        ),
    ]
