# Generated by Django 5.1.2 on 2024-11-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_subs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subs",
            name="is_subs",
            field=models.BooleanField(
                default=True, verbose_name="Пользователь подписан"
            ),
        ),
    ]
