# Generated by Django 5.1.2 on 2024-11-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_subs_is_subs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subs",
            name="is_subs",
        ),
    ]
